require "minitest/autorun"
require "minitest/rg"
require "sinatra/activerecord"
require_relative "../app/models/band_members.rb"
require_relative "../app/models/set_item.rb"
require_relative "../app/models/set_list.rb"
require_relative "../app/models/venue.rb"
require_relative "../app/models/song.rb"
