development:
  host: 'localhost'
  adapter: 'postgresql'
  database: 'set-list-manager'
  encoding: 'utf8'
  pool: 5
test:
  host: 'localhost'
  adapter: 'postgresql'
  database: 'set-list-manager-test'
  encoding: 'utf8'
  pool: 5
